server:
  servlet:
    port: 8080
    context-path: /api

spring:
  application:
    name: proman-api
  datasource:
      url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: 1234
      driver-class-name: org.postgresql.Driver




jpa:
  properties:
    hibernate:
      temp:
        use_jdbc_metadata_defaults: false
      database-platform: org.hibernate.dialect.PostgreSQL9Dialect